name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Ambil kode dari GitHub
      - name: Checkout kode
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Cek kualitas kode (lint)
      - name: Lint
        run: npm run lint

      # 5. Build project
      - name: Build
        run: npm run build
        env:
          # Kalau punya env variable, tambahkan di sini
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_MIDTRANS_CLIENT_KEY: ${{ secrets.VITE_MIDTRANS_CLIENT_KEY }}
          VITE_FRONTEND_URL: ${{ secrets.VITE_FRONTEND_URL }}
          VITE_AUTH_URL: ${{ secrets.VITE_AUTH_URL }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}

      # 6. Deploy ke server via SSH
      - name: Deploy ke CyberPanel
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/"
          target: "/home/petikniaga.psjpetik.my.id/public_html"
          strip_components: 1
